(******************************************************************************)
(*                                                                            *)
(*          Eurocode 8: Seismic Design Verification Predicates                *)
(*                                                                            *)
(*     Formalizes EN 1998-1-1:2024 seismic action definitions, response       *)
(*     spectrum construction, lateral force method, and ductility class        *)
(*     compliance checks. Structural safety as decidable predicates.          *)
(*                                                                            *)
(*     "Nature had not assembled twenty thousand houses of six or seven       *)
(*     storeys there. If the inhabitants had been more equally dispersed,     *)
(*     the damage would have been much less, and perhaps nothing at all."     *)
(*     - Jean-Jacques Rousseau, Letter to Voltaire, 1756                     *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: February 22, 2026                                                *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
